[package]
name = "cosine_benchmark_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "=1.8.1"
rayon-core = "=1.12.1"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
